export type RootStackParamList = {
  Login: undefined;
  Register: undefined;
  Dashboard: undefined;
  Sites: undefined;
  MySite: undefined;
  Inventory: undefined;
  MaterialRequests: undefined;
  RequestDetails: { requestId: string };
  StockIn: undefined;
  StockOut: undefined;
  Deliveries: undefined;
  DeliveryDetails: { deliveryId: string };
  PhotoMonitoring: undefined;
  SiteMapView: undefined;
  LowStockAlert: undefined;
  Reports: undefined;
  Profile: undefined;
  MoreMenu: undefined;
};
