export type RootStackParamList = {
  Login: undefined;
  Register: undefined;
  Dashboard: undefined;
  ProjectMaster: undefined;
  SupervisorMaster: undefined;
  ProjectDuration: undefined;
  InventoryMaster: undefined;
  MaterialInward: undefined;
  MaterialOutward: undefined;
  LabourEntry: undefined;
  Sites: undefined;
  MySite: undefined;
  Inventory: undefined;
  LowStockAlert: undefined;
  Reports: undefined;
  Profile: undefined;
  MoreMenu: undefined;
  PrivacyPolicy: undefined;
  TermsConditions: undefined;
};
